### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by Sphynxcolt** [Paulao17/MindustryModCreator#9]
Please add a dark mode lol

**Comment by Sphynxcolt** [comment]
So if its not your priority, then just dont work on it. I can do it myself and then make a pull request if you want to.

**Comment by ignyx** [comment]
Have a look at `.bg-dark`. See [docs](https://getbootstrap.com/docs/4.0/utilities/colors/#color)

**Comment by ignyx** [comment]
Resolved by #12
